package tests
package tests

import (
	"openrisk/internal/core/domain"
)

// MockRoleRepository is a mock implementation of RoleRepository
type MockRoleRepository struct {









































































































}	return tenants	}		tenants = append(tenants, tenant)	for _, tenant := range m.tenants {	tenants := make([]domain.Tenant, )func (m MockTenantRepository) ListTenants() []domain.Tenant {// ListTenants returns all tenants}	delete(m.tenants, id)func (m MockTenantRepository) DeleteTenant(id string) {// DeleteTenant deletes a tenant from the mock repository}	return m.tenants[id]func (m MockTenantRepository) GetTenant(id string) domain.Tenant {// GetTenant retrieves a tenant from the mock repository}	m.tenants[tenant.ID] = tenantfunc (m MockTenantRepository) SetTenant(tenant domain.Tenant) {// SetTenant sets a tenant in the mock repository}	}		tenants: make(map[string]domain.Tenant),	return &MockTenantRepository{func NewMockTenantRepository() MockTenantRepository {// NewMockTenantRepository creates a new mock tenant repository}	tenants map[string]domain.Tenanttype MockTenantRepository struct {// MockTenantRepository is a mock implementation of TenantRepository}	return perms	}		perms = append(perms, perm)	for _, perm := range m.permissions {	perms := make([]domain.Permission, )func (m MockPermissionRepository) ListPermissions() []domain.Permission {// ListPermissions returns all permissions}	delete(m.permissions, id)func (m MockPermissionRepository) DeletePermission(id string) {// DeletePermission deletes a permission from the mock repository}	return m.permissions[id]func (m MockPermissionRepository) GetPermission(id string) domain.Permission {// GetPermission retrieves a permission from the mock repository}	m.permissions[perm.ID] = permfunc (m MockPermissionRepository) SetPermission(perm domain.Permission) {// SetPermission sets a permission in the mock repository}	}		permissions: make(map[string]domain.Permission),	return &MockPermissionRepository{func NewMockPermissionRepository() MockPermissionRepository {// NewMockPermissionRepository creates a new mock permission repository}	permissions map[string]domain.Permissiontype MockPermissionRepository struct {// MockPermissionRepository is a mock implementation of PermissionRepository}	return roles	}		roles = append(roles, role)	for _, role := range m.roles {	roles := make([]domain.Role, )func (m MockRoleRepository) ListRoles() []domain.Role {// ListRoles returns all roles}	delete(m.roles, id)func (m MockRoleRepository) DeleteRole(id string) {// DeleteRole deletes a role from the mock repository}	return m.roles[id]func (m MockRoleRepository) GetRole(id string) domain.Role {// GetRole retrieves a role from the mock repository}	m.roles[role.ID] = rolefunc (m MockRoleRepository) SetRole(role domain.Role) {// SetRole sets a role in the mock repository}	}		roles: make(map[string]domain.Role),	return &MockRoleRepository{func NewMockRoleRepository() MockRoleRepository {// NewMockRoleRepository creates a new mock role repository}	roles map[string]domain.Role