package tests
package tests

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"openrisk/internal/core/domain"
	"openrisk/internal/core/service"































































































































































































































































































































































































































































}	}		svc.MatchPermission("roles:read", "roles:*")		svc.MatchPermission("users:write", "*:*")		svc.MatchPermission("users:read", "users:read")	for i := 0; i < b.N; i++ {	b.ResetTimer()	svc := service.NewPermissionService(repo)	repo := NewMockPermissionRepository()func BenchmarkPermissionServiceMatching(b *testing.B) {// BenchmarkPermissionServiceMatching benchmarks permission matching}	}		svc.CanUserAccess(ctx, "user-1", "users:read")	for i := 0; i < b.N; i++ {	b.ResetTimer()	repo.SetPermission(perm)	}		Action:   "read",		Resource: "users",		ID:       "bench-perm",	perm := &domain.Permission{	ctx := context.Background()	svc := service.NewPermissionService(repo)	repo := NewMockPermissionRepository()func BenchmarkPermissionServiceCheck(b *testing.B) {// BenchmarkPermissionServiceCheck benchmarks permission checking}	})		}			assert.Nil(t, retrieved)			retrieved, _ := svc.GetByID(ctx, id)		for _, id := range ids {		assert.NoError(t, err)		// Assert		err := svc.BulkDelete(ctx, ids)		// Execute		}			})				Action:   "read",				Resource: "test",				ID:       id,			repo.SetPermission(&domain.Permission{		for _, id := range ids {		ids := []string{"p1", "p2", "p3"}		// Create permissions		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("bulk_delete_permissions", func(t *testing.T) {	})		assert.Equal(t, 3, len(created))		assert.NoError(t, err)		// Assert		created, err := svc.BulkCreate(ctx, perms)		// Execute		}			{Resource: "roles", Action: "read"},			{Resource: "users", Action: "write"},			{Resource: "users", Action: "read"},		perms := []*domain.Permission{		// Test data		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("bulk_create_permissions", func(t *testing.T) {func TestPermissionServiceBulkOperations(t *testing.T) {// TestPermissionServiceBulkOperations tests bulk permission operations}	})		assert.True(t, matches)		matches := svc.MatchPermission("anything:anywhen", "*:*")		// Test full wildcard		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("match_full_wildcard", func(t *testing.T) {	})		assert.True(t, matches)		matches = svc.MatchPermission("users:write", "users:*")		assert.True(t, matches)		matches := svc.MatchPermission("users:read", "users:*")		// Test wildcard matching		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("match_wildcard_action", func(t *testing.T) {	})		assert.True(t, matches)		matches = svc.MatchPermission("roles:read", "*:read")		assert.True(t, matches)		matches := svc.MatchPermission("users:read", "*:read")		// Test wildcard matching		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("match_wildcard_resource", func(t *testing.T) {	})		assert.False(t, noMatch)		noMatch := svc.MatchPermission("users:read", "users:write")		assert.True(t, matches)		matches := svc.MatchPermission("users:read", "users:read")		// Test matching		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("match_exact_permission", func(t *testing.T) {func TestPermissionServiceMatching(t *testing.T) {// TestPermissionServiceMatching tests permission matching logic}	})		assert.Error(t, err)		// Assert		err := svc.Delete(ctx, "nonexistent")		// Execute		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("delete_nonexistent_permission", func(t *testing.T) {	})		assert.Nil(t, retrieved)		retrieved, _ := svc.GetByID(ctx, "perm-del")		// Verify deletion		assert.NoError(t, err)		// Assert		err := svc.Delete(ctx, "perm-del")		// Execute		repo.SetPermission(perm)		}			Action:   "read",			Resource: "users",			ID:       "perm-del",		perm := &domain.Permission{		// Create permission		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("delete_permission", func(t *testing.T) {func TestPermissionServiceDelete(t *testing.T) {// TestPermissionServiceDelete tests permission deletion}	})		assert.Contains(t, err.Error(), "cannot modify resource or action")		assert.Nil(t, updated)		assert.Error(t, err)		// Assert		updated, err := svc.Update(ctx, perm)		// Execute		perm.Action = "write"		perm.Resource = "roles"		// Try to update immutable fields		repo.SetPermission(perm)		}			Action:   "read",			Resource: "users",			ID:       "perm-fixed",		perm := &domain.Permission{		// Create permission		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("update_permission_cannot_change_resource_action", func(t *testing.T) {	})		assert.Equal(t, "New description", updated.Description)		assert.NotNil(t, updated)		assert.NoError(t, err)		// Assert		updated, err := svc.Update(ctx, perm)		// Execute		perm.Description = "New description"		// Update		repo.SetPermission(perm)		}			Description: "Old description",			Action:      "read",			Resource:    "users",			ID:          "perm-update",		perm := &domain.Permission{		// Create permission		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("update_permission_description", func(t *testing.T) {func TestPermissionServiceUpdate(t *testing.T) {// TestPermissionServiceUpdate tests permission updates}	})		assert.Equal(t, 2, len(retrieved))		assert.NoError(t, err)		// Assert		retrieved, err := svc.ListByResource(ctx, "users")		// Execute		}			repo.SetPermission(p)		for _, p := range perms {		}			{ID: "p3", Resource: "roles", Action: "read"},			{ID: "p2", Resource: "users", Action: "write"},			{ID: "p1", Resource: "users", Action: "read"},		perms := []*domain.Permission{		// Create test permissions		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("list_permissions_by_resource", func(t *testing.T) {	})		assert.Equal(t, 3, len(retrieved))		assert.NoError(t, err)		// Assert		retrieved, err := svc.List(ctx, 0, 10)		// Execute		}			repo.SetPermission(p)		for _, p := range perms {		}			{ID: "p3", Resource: "roles", Action: "read"},			{ID: "p2", Resource: "users", Action: "write"},			{ID: "p1", Resource: "users", Action: "read"},		perms := []*domain.Permission{		// Create test permissions		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("list_all_permissions", func(t *testing.T) {func TestPermissionServiceList(t *testing.T) {// TestPermissionServiceList tests permission listing}	})		assert.True(t, hasAccess)		// Assert		hasAccess := svc.CanUserAccess(ctx, "admin-user", "*:*")		// Execute		repo.SetPermission(perm)		}			Action:   "*",			Resource: "*",			ID:       "perm-admin",		perm := &domain.Permission{		// Create wildcard permission		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("check_wildcard_permission", func(t *testing.T) {	})		assert.False(t, hasAccess)		// Assert		hasAccess := svc.CanUserAccess(ctx, "user-1", "admin:delete")		// Execute		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("check_user_missing_permission", func(t *testing.T) {	})		assert.True(t, hasAccess)		// Assert		hasAccess := svc.CanUserAccess(ctx, "user-1", "risks:read")		// Execute		repo.SetPermission(perm)		}			Action:   "read",			Resource: "risks",			ID:       "perm-read",		perm := &domain.Permission{		// Create permission		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("check_user_has_permission", func(t *testing.T) {func TestPermissionServiceCheck(t *testing.T) {// TestPermissionServiceCheck tests permission verification}	})		assert.Contains(t, err.Error(), "permission already exists")		assert.Nil(t, created)		assert.Error(t, err)		// Assert		created, err := svc.Create(ctx, duplicate)		// Execute		}			Description: "Duplicate",			Action:      "read",			Resource:    "users",		duplicate := &domain.Permission{		// Try to create duplicate		repo.SetPermission(perm)		}			Description: "Read users",			Action:      "read",			Resource:    "users",			ID:          "perm-1",		perm := &domain.Permission{		// Create first permission		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("create_duplicate_permission_fails", func(t *testing.T) {	})		assert.Contains(t, err.Error(), "action is required")		assert.Nil(t, created)		assert.Error(t, err)		// Assert		created, err := svc.Create(ctx, perm)		// Execute		}			Description: "Invalid",			Action:      "",			Resource:    "users",		perm := &domain.Permission{		// Test data		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("create_permission_missing_action", func(t *testing.T) {	})		assert.Contains(t, err.Error(), "resource is required")		assert.Nil(t, created)		assert.Error(t, err)		// Assert		created, err := svc.Create(ctx, perm)		// Execute		}			Description: "Invalid",			Action:      "read",			Resource:    "",		perm := &domain.Permission{		// Test data		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("create_permission_missing_resource", func(t *testing.T) {	})		assert.Equal(t, "read", created.Action)		assert.Equal(t, "users", created.Resource)		assert.NotEmpty(t, created.ID)		assert.NotNil(t, created)		assert.NoError(t, err)		// Assert		created, err := svc.Create(ctx, perm)		// Execute		}			Description: "Read users",			Action:   "read",			Resource: "users",		perm := &domain.Permission{		// Test data		ctx := context.Background()		svc := service.NewPermissionService(repo)		repo := NewMockPermissionRepository()		// Setup	t.Run("create_valid_permission", func(t *testing.T) {func TestPermissionServiceCreate(t *testing.T) {// TestPermissionServiceCreate tests permission creation)