/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check API health status
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all risks */
        get: operations["listRisks"];
        put?: never;
        /** Create a new risk */
        post: operations["createRisk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get risk details */
        get: operations["getRisk"];
        put?: never;
        post?: never;
        /** Delete risk */
        delete: operations["deleteRisk"];
        options?: never;
        head?: never;
        /** Update risk */
        patch: operations["updateRisk"];
        trace?: never;
    };
    "/risks/{id}/mitigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add mitigation to risk */
        post: operations["addMitigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mitigations/{mitigationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update mitigation details */
        patch: operations["updateMitigation"];
        trace?: never;
    };
    "/mitigations/{mitigationId}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle mitigation status (PLANNED ↔ DONE) */
        patch: operations["toggleMitigationStatus"];
        trace?: never;
    };
    "/mitigations/{id}/subactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create mitigation sub-action (checklist item) */
        post: operations["createMitigationSubAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mitigations/{id}/subactions/{subactionId}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle sub-action completed status */
        patch: operations["toggleSubAction"];
        trace?: never;
    };
    "/mitigations/{id}/subactions/{subactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete mitigation sub-action */
        delete: operations["deleteSubAction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mitigations/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recommended mitigations (sorted by SPP score) */
        get: operations["getRecommendedMitigations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List regulatory control catalogs available to import (M2)
         * @description Static reference data (e.g. ISO 27001:2022's 93 Annex A controls) that can be bulk-imported into a tenant's own framework via POST /compliance/frameworks/{frameworkId}/import-catalog. Includes catalogs that are registered but not yet available (control_count: 0, available: false) so clients can show them as "coming soon" — see ROADMAP.md M2 for why COBAC/BCEAO/ANSSI-CM aren't modeled yet.
         */
        get: operations["listComplianceCatalogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/frameworks/{frameworkId}/import-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-import a regulatory catalog's controls into a framework (admin only, M2)
         * @description Idempotent — controls already present (matched by reference_code) are skipped, so calling this again after a catalog is extended only creates what's new.
         */
        post: operations["importComplianceCatalog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/frameworks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List global compliance frameworks */
        get: operations["listComplianceFrameworks"];
        put?: never;
        /** Create a global compliance framework (admin only) */
        post: operations["createComplianceFramework"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/frameworks/{frameworkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a compliance framework */
        get: operations["getComplianceFramework"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/frameworks/{frameworkId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant's compliance progress for a framework */
        get: operations["getComplianceProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/frameworks/{frameworkId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download an official compliance report (PDF) for a framework
         * @description Generates, in a single click, a print-ready PDF compliance report for the framework: cover identity (organization, framework, date, requester), an executive summary (compliance %, per-status breakdown) and a detailed, paginated controls table (reference, name, status, evidence count, source citation). All data is strictly tenant-scoped — the framework is global but only the requesting tenant's controls and evidence appear. Suitable for COBAC/BCEAO/ISO one-click statements.
         */
        get: operations["generateComplianceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/frameworks/{frameworkId}/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a tenant's controls for a framework */
        get: operations["listComplianceControls"];
        put?: never;
        /** Instantiate a control for a tenant under this framework */
        post: operations["createComplianceControl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/controls/{controlId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a control */
        get: operations["getComplianceControl"];
        put?: never;
        post?: never;
        /** Delete a control (admin only) */
        delete: operations["deleteComplianceControl"];
        options?: never;
        head?: never;
        /** Update a control (notably its implementation status) */
        patch: operations["updateComplianceControl"];
        trace?: never;
    };
    "/compliance/controls/{controlId}/evidences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evidence attached to a control */
        get: operations["listComplianceEvidences"];
        put?: never;
        /** Upload a file as evidence for a control */
        post: operations["createComplianceEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/evidences/{evidenceId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download an evidence file
         * @description The only path to evidence file content — there is no public/static
         *     URL. Tenant ownership is re-verified on every call.
         */
        get: operations["downloadComplianceEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/evidences/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an evidence record and its file (admin only) */
        delete: operations["deleteComplianceEvidence"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all assets */
        get: operations["listAssets"];
        put?: never;
        /** Create asset */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get asset by ID */
        get: operations["getAsset"];
        put?: never;
        post?: never;
        /** Delete asset */
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        /** Update asset */
        patch: operations["updateAsset"];
        trace?: never;
    };
    "/assets/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get asset history (snapshots taken before each update/delete) */
        get: operations["getAssetHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard statistics */
        get: operations["getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/risk-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get risk matrix data (impact vs probability) */
        get: operations["getRiskMatrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get global risk trend */
        get: operations["getRiskTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export risks to PDF */
        get: operations["exportPDF"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gamification/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's gamification profile */
        get: operations["getGamificationProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginInput: {
            /**
             * Format: email
             * @example admin@example.com
             */
            email: string;
            /**
             * Format: password
             * @example password123
             */
            password: string;
        };
        CreateRiskInput: {
            /** @example Data breach risk */
            title: string;
            /** @example Unauthorized access to sensitive customer data */
            description?: string;
            /**
             * @description Impact level (1-5)
             * @example 5
             */
            impact: number;
            /**
             * @description Probability level (1-5)
             * @example 3
             */
            probability: number;
            /**
             * @example [
             *       "security",
             *       "data-protection"
             *     ]
             */
            tags?: string[];
            asset_ids?: string[];
            /**
             * @example ISO27001
             * @enum {string}
             */
            framework?: "ISO27001" | "CIS" | "NIST" | "OWASP";
        };
        UpdateRiskInput: {
            title?: string;
            description?: string;
            impact?: number;
            probability?: number;
            tags?: string[];
            asset_ids?: string[];
        };
        CreateMitigationInput: {
            /** @example Implement encryption */
            title: string;
            /** @example security-team@example.com */
            assignee?: string;
            /** @example 50 */
            progress?: number;
            /** @example High */
            cost?: string;
            /** @example 2025-12-31 */
            mitigation_time?: string;
            /**
             * Format: date
             * @example 2025-12-31
             */
            due_date?: string;
        };
        UpdateMitigationInput: {
            title?: string;
            assignee?: string;
            progress?: number;
            cost?: string;
            mitigation_time?: string;
            /** Format: date */
            due_date?: string;
        };
        CreateSubActionInput: {
            /** @example Install security patches */
            title: string;
        };
        CreateAssetInput: {
            /** @example Production Database Server */
            name: string;
            /**
             * @example Database
             * @enum {string}
             */
            type?: "Server" | "Laptop" | "Database" | "SaaS" | "Network" | "Storage";
            /**
             * @example CRITICAL
             * @enum {string}
             */
            criticality?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** @example DBA Team */
            owner?: string;
            /** @example db-prod-001 */
            external_id?: string;
        };
        /** @description Partial update — omitted fields are left unchanged. */
        UpdateAssetInput: {
            name?: string;
            /** @enum {string} */
            type?: "Server" | "Laptop" | "Database" | "SaaS" | "Network" | "Storage";
            /** @enum {string} */
            criticality?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            owner?: string;
        };
        AuthResponse: {
            /**
             * @description JWT Bearer token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token?: string;
            user?: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            full_name?: string;
            /** @enum {string} */
            role?: "ADMIN" | "ANALYST" | "VIEWER";
            /** Format: uri */
            avatar_url?: string;
            /** Format: date-time */
            last_login?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Risk: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            impact?: number;
            probability?: number;
            /**
             * Format: float
             * @description Calculated risk score
             */
            score?: number;
            /** @enum {string} */
            status?: "OPEN" | "MITIGATED" | "ACCEPTED" | "CLOSED";
            /** @enum {string} */
            framework?: "ISO27001" | "CIS" | "NIST" | "OWASP";
            tags?: string[];
            assets?: components["schemas"]["Asset"][];
            mitigations?: components["schemas"]["Mitigation"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Mitigation: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            risk_id?: string;
            title?: string;
            /** @enum {string} */
            status?: "PLANNED" | "IN_PROGRESS" | "DONE";
            assignee?: string;
            progress?: number;
            cost?: string;
            mitigation_time?: string;
            /** Format: date */
            due_date?: string;
            sub_actions?: components["schemas"]["MitigationSubAction"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MitigationSubAction: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            mitigation_id?: string;
            title?: string;
            completed?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description Global reference entity (not tenant-scoped), e.g. ISO 27001, COBAC. */
        ComplianceFramework: {
            /** Format: uuid */
            id: string;
            name: string;
            version: string;
            description?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateFrameworkInput: {
            name: string;
            version?: string;
            description?: string;
        };
        /** @description Tenant-scoped control instantiated under a global framework. */
        ComplianceControl: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            framework_id: string;
            /** @example A.5.1.1 */
            reference_code: string;
            name: string;
            description?: string;
            /**
             * @description Citation for where this control comes from (standard section, circular article, law) — populated on catalog-imported controls, optional for ad-hoc ones.
             * @example ISO/IEC 27001:2022, Annexe A, A.5.1
             */
            source_reference?: string;
            /** @enum {string} */
            status: "not_implemented" | "in_progress" | "implemented" | "not_applicable";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateControlInput: {
            reference_code?: string;
            name: string;
            description?: string;
            source_reference?: string;
        };
        /** @description Partial update — omitted fields are left unchanged. */
        UpdateControlInput: {
            reference_code?: string;
            name?: string;
            description?: string;
            source_reference?: string;
            /** @enum {string} */
            status?: "not_implemented" | "in_progress" | "implemented" | "not_applicable";
        };
        /** @description A regulatory control catalog available (or not yet available) for import. */
        ComplianceCatalogSummary: {
            /** @example iso27001-2022 */
            key: string;
            /** @example ISO/IEC 27001 */
            name: string;
            /** @example 2022 */
            version?: string;
            description?: string;
            /** @description False for placeholder catalogs with no reviewed control content yet. */
            available: boolean;
            control_count: number;
        };
        ImportCatalogInput: {
            /** @example iso27001-2022 */
            catalog_key: string;
        };
        ImportCatalogResult: {
            /** @description Controls newly created by this call. */
            imported: number;
            /** @description Controls that already existed (matched by reference_code) and were left untouched. */
            skipped: number;
            /** @description Total controls in the catalog. */
            total: number;
        };
        /** @description Tenant-scoped evidence file attached to a control. */
        ControlEvidence: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            control_id: string;
            filename: string;
            description?: string;
            /** Format: uuid */
            uploaded_by?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Computed, not persisted — tallies a tenant's controls for a framework by status. */
        ComplianceProgress: {
            /** Format: uuid */
            framework_id: string;
            total: number;
            /**
             * @example {
             *       "not_implemented": 2,
             *       "in_progress": 2,
             *       "implemented": 4,
             *       "not_applicable": 2
             *     }
             */
            by_status: {
                [key: string]: number;
            };
            /** @description total minus not_applicable */
            applicable: number;
            /**
             * Format: float
             * @description implemented / applicable * 100 (0 if applicable is 0)
             */
            percent_complete: number;
        };
        Asset: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            type?: "Server" | "Laptop" | "Database" | "SaaS" | "Network" | "Storage";
            /** @enum {string} */
            criticality?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            owner?: string;
            /** @enum {string} */
            source?: "MANUAL" | "OPENASSET";
            external_id?: string;
            risks?: components["schemas"]["Risk"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description An asset's state captured immediately before an update or deletion. */
        AssetSnapshot: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            asset_id?: string;
            name?: string;
            type?: string;
            /** @enum {string} */
            criticality?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            owner?: string;
            /** @enum {string} */
            reason?: "update" | "delete";
            /** Format: date-time */
            created_at?: string;
        };
        DashboardStats: {
            total_risks?: number;
            open_risks?: number;
            mitigated_risks?: number;
            accepted_risks?: number;
            closed_risks?: number;
            /** Format: float */
            average_risk_score?: number;
            critical_assets?: number;
            recent_risks?: components["schemas"]["Risk"][];
        };
        GamificationProfile: {
            /** Format: uuid */
            user_id?: string;
            points?: number;
            level?: number;
            badges?: {
                name?: string;
                /** Format: date-time */
                earned_at?: string;
            }[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ErrorResponse: {
            /** @example Invalid input */
            error?: string;
            /** @example 400 */
            code?: number;
            details?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example UP */
                        status?: string;
                        /** @example 1.0.0 */
                        version?: string;
                        /** @example CONNECTED */
                        db?: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRisks: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sort_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of risks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Risk"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRisk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRiskInput"];
            };
        };
        responses: {
            /** @description Risk created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Risk"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRisk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Risk UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risk details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Risk"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Risk not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteRisk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risk deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Risk not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRisk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRiskInput"];
            };
        };
        responses: {
            /** @description Risk updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Risk"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Risk not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addMitigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Risk UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMitigationInput"];
            };
        };
        responses: {
            /** @description Mitigation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitigation"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Risk not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMitigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mitigationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMitigationInput"];
            };
        };
        responses: {
            /** @description Mitigation updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitigation"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mitigation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggleMitigationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mitigationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitigation"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mitigation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createMitigationSubAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mitigation UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubActionInput"];
            };
        };
        responses: {
            /** @description Sub-action created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MitigationSubAction"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mitigation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggleSubAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mitigation UUID */
                id: string;
                /** @description Sub-action UUID */
                subactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sub-action toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MitigationSubAction"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sub-action not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSubAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mitigation UUID */
                id: string;
                /** @description Sub-action UUID */
                subactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sub-action deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sub-action not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRecommendedMitigations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommended mitigations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitigation"][];
                };
            };
        };
    };
    listComplianceCatalogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of catalogs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceCatalogSummary"][];
                };
            };
        };
    };
    importComplianceCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frameworkId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportCatalogInput"];
            };
        };
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportCatalogResult"];
                };
            };
            /** @description Unknown catalog key, or the catalog is not yet available */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — only Admin can import a catalog (same tier as creating a framework) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Framework not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listComplianceFrameworks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of frameworks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceFramework"][];
                };
            };
        };
    };
    createComplianceFramework: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFrameworkInput"];
            };
        };
        responses: {
            /** @description Framework created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceFramework"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — only Admin can create a global framework */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A framework with this name and version already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getComplianceFramework: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frameworkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Framework */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceFramework"];
                };
            };
            /** @description Framework not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getComplianceProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frameworkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceProgress"];
                };
            };
        };
    };
    generateComplianceReport: {
        parameters: {
            query?: {
                /** @description Fixed-label language of the report. Defaults to French. */
                locale?: "fr" | "en";
            };
            header?: never;
            path: {
                frameworkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The compliance report as a PDF attachment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Framework not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listComplianceControls: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frameworkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of controls */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceControl"][];
                };
            };
        };
    };
    createComplianceControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                frameworkId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateControlInput"];
            };
        };
        responses: {
            /** @description Control created (status defaults to not_implemented) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceControl"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Framework not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A control with this reference_code already exists for this tenant+framework */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getComplianceControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                controlId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceControl"];
                };
            };
            /** @description Control not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteComplianceControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                controlId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — Delete is admin-only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Control not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateComplianceControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                controlId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateControlInput"];
            };
        };
        responses: {
            /** @description Control updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceControl"];
                };
            };
            /** @description Invalid status value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Control not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listComplianceEvidences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                controlId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlEvidence"][];
                };
            };
        };
    };
    createComplianceEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                controlId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    description?: string;
                };
            };
        };
        responses: {
            /** @description Evidence uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlEvidence"];
                };
            };
            /** @description Missing file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Control not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadComplianceEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Evidence not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteComplianceEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — Delete is admin-only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Evidence not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetInput"];
            };
        };
        responses: {
            /** @description Asset created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            /** @description Asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetInput"];
            };
        };
        responses: {
            /** @description Asset updated. If criticality changed, every linked risk's score is recalculated asynchronously by the Score Engine worker. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAssetHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset history, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSnapshot"][];
                };
            };
            /** @description Asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRiskMatrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risk matrix data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        matrix?: Record<string, never>;
                    };
                };
            };
        };
    };
    getRiskTrend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risk trend data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    exportPDF: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGamificationProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gamification profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamificationProfile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
