// Copyright (c) 2026 OpenDefender Contributors
// SPDX-License-Identifier: BUSL-1.1
// This Source Code Form is subject to the terms of the Business Source License, Version 1.1.
// If a copy of the BUSL was not distributed with this file, You can obtain one at https://mariadb.com/bsl11/

package report

import (
	"bytes"
	"fmt"
	"time"

	"github.com/go-pdf/fpdf"
)

// Risk-criticality accent colors (board report only).
var (
	critRed    = rgb{220, 38, 38}   // critical
	critOrange = rgb{234, 88, 12}   // high
	critAmber  = rgb{202, 138, 4}   // medium
	critGreen  = rgb{22, 163, 74}   // low
	cardBg     = rgb{248, 250, 252} // slate-50
)

// boardLabels holds every fixed (non-data) string of a board report, per locale.
type boardLabels struct {
	docTitle       string
	subtitle       string
	organization   string
	period         string
	generatedAt    string
	generatedBy    string
	writtenBy      string
	statusDraft    string
	statusApproved string
	approvedBy     string
	postureTitle   string
	kpiCompliance  string
	kpiRisks       string
	kpiExposure    string
	critical       string
	high           string
	medium         string
	low            string
	execTitle      string
	riskTitle      string
	compTitle      string
	finTitle       string
	recoTitle      string
	frameworksHdr  string
	noFrameworks   string
	draftBanner    string
	confidential   string
	page           string
	dateLayout     string
}

func boardLabelsFor(l Locale) boardLabels {
	if l == LocaleEN {
		return boardLabels{
			docTitle:       "BOARD REPORT",
			subtitle:       "Risk & compliance posture for the board of directors",
			organization:   "Organization",
			period:         "Period",
			generatedAt:    "Generated on",
			generatedBy:    "Prepared by",
			writtenBy:      "Narrative by",
			statusDraft:    "DRAFT",
			statusApproved: "APPROVED",
			approvedBy:     "Approved by",
			postureTitle:   "Posture at a glance",
			kpiCompliance:  "Compliance",
			kpiRisks:       "Active risks",
			kpiExposure:    "Est. annual exposure",
			critical:       "Critical",
			high:           "High",
			medium:         "Medium",
			low:            "Low",
			execTitle:      "Executive summary",
			riskTitle:      "Risk posture",
			compTitle:      "Regulatory compliance",
			finTitle:       "Financial exposure",
			recoTitle:      "Recommendations",
			frameworksHdr:  "Compliance by framework",
			noFrameworks:   "No compliance framework is tracked yet.",
			draftBanner:    "DRAFT — for internal review, not for distribution",
			confidential:   "Confidential - generated by OpenRisk",
			page:           "Page",
			dateLayout:     "Jan 02, 2006 15:04 MST",
		}
	}
	return boardLabels{
		docTitle:       "RAPPORT DU CONSEIL",
		subtitle:       "Posture de risque et de conformité pour le conseil d'administration",
		organization:   "Organisation",
		period:         "Période",
		generatedAt:    "Généré le",
		generatedBy:    "Préparé par",
		writtenBy:      "Rédaction",
		statusDraft:    "BROUILLON",
		statusApproved: "APPROUVÉ",
		approvedBy:     "Approuvé par",
		postureTitle:   "Posture en un coup d'œil",
		kpiCompliance:  "Conformité",
		kpiRisks:       "Risques actifs",
		kpiExposure:    "Exposition annuelle est.",
		critical:       "Critique",
		high:           "Élevé",
		medium:         "Moyen",
		low:            "Faible",
		execTitle:      "Synthèse exécutive",
		riskTitle:      "Posture de risque",
		compTitle:      "Conformité réglementaire",
		finTitle:       "Exposition financière",
		recoTitle:      "Recommandations",
		frameworksHdr:  "Conformité par référentiel",
		noFrameworks:   "Aucun référentiel de conformité n'est encore suivi.",
		draftBanner:    "BROUILLON — revue interne, non diffusable",
		confidential:   "Confidentiel — généré par OpenRisk",
		page:           "Page",
		dateLayout:     "02/01/2006 15:04 MST",
	}
}

// RenderBoardPDF renders a monthly board report to PDF bytes. It is pure: no I/O
// beyond building the in-memory document. Reuses the shared drawing helpers and
// palette defined alongside the compliance report.
func RenderBoardPDF(data BoardReportData) ([]byte, error) {
	lbl := boardLabelsFor(data.Locale.normalize())

	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(pageMarginLeft, pageMarginTop, pageMarginRight)
	pdf.SetAutoPageBreak(true, pageMarginBottom)
	pdf.AliasNbPages("{nb}")

	tr := pdf.UnicodeTranslatorFromDescriptor("")

	isDraft := data.Status != "approved"

	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Arial", "", 8)
		setText(pdf, textMuted)
		left := lbl.confidential
		if isDraft {
			left = lbl.draftBanner
		}
		pdf.CellFormat(usableWidth/2, 6, tr(left), "", 0, "L", false, 0, "")
		pdf.CellFormat(usableWidth/2, 6,
			fmt.Sprintf("%s %d/{nb}", lbl.page, pdf.PageNo()),
			"", 0, "R", false, 0, "")
	})

	pdf.AddPage()
	drawBoardHeader(pdf, tr, lbl)
	drawBoardIdentity(pdf, tr, lbl, data)
	drawBoardKPIs(pdf, tr, lbl, data)
	drawBoardSection(pdf, tr, lbl.execTitle, data.ExecutiveSummary)
	drawBoardSection(pdf, tr, lbl.riskTitle, data.RiskCommentary)
	drawRiskChips(pdf, tr, lbl, data)
	drawBoardSection(pdf, tr, lbl.compTitle, data.ComplianceCommentary)
	drawFrameworksTable(pdf, tr, lbl, data)
	drawBoardSection(pdf, tr, lbl.finTitle, data.FinancialCommentary)
	drawRecommendations(pdf, tr, lbl, data)

	if pdf.Err() {
		return nil, fmt.Errorf("board pdf render error: %w", pdf.Error())
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("board pdf output error: %w", err)
	}
	return buf.Bytes(), nil
}

func drawBoardHeader(pdf *fpdf.Fpdf, tr func(string) string, lbl boardLabels) {
	setFill(pdf, brandDark)
	pdf.Rect(0, 0, 210, 32, "F")
	setFill(pdf, brandAccent)
	pdf.Rect(0, 32, 210, 1.5, "F")

	pdf.SetY(9)
	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "B", 20)
	setText(pdf, rgb{255, 255, 255})
	pdf.CellFormat(usableWidth, 9, tr(lbl.docTitle), "", 1, "L", false, 0, "")

	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "", 10)
	setText(pdf, rgb{203, 213, 225})
	pdf.CellFormat(usableWidth, 6, tr("OpenRisk  -  "+lbl.subtitle), "", 1, "L", false, 0, "")

	pdf.SetY(40)
}

func drawBoardIdentity(pdf *fpdf.Fpdf, tr func(string) string, lbl boardLabels, data BoardReportData) {
	// Status badge (top-right of the identity block).
	badge := lbl.statusApproved
	badgeColor := green
	if data.Status != "approved" {
		badge = lbl.statusDraft
		badgeColor = amber
	}
	badgeW := pdf.GetStringWidth(tr(badge)) + 8
	pdf.SetFont("Arial", "B", 9)
	setFill(pdf, badgeColor)
	setText(pdf, rgb{255, 255, 255})
	pdf.SetXY(210-pageMarginRight-badgeW, 41)
	pdf.CellFormat(badgeW, 6, tr(badge), "", 0, "C", true, 0, "")

	line := func(label, value string) {
		if value == "" {
			return
		}
		pdf.SetX(pageMarginLeft)
		pdf.SetFont("Arial", "B", 10)
		setText(pdf, textMuted)
		pdf.CellFormat(42, 6, tr(label), "", 0, "L", false, 0, "")
		pdf.SetFont("Arial", "", 10)
		setText(pdf, textDark)
		pdf.CellFormat(usableWidth-42-badgeW-2, 6, tr(value), "", 1, "L", false, 0, "")
	}

	org := data.OrganizationName
	if org == "" {
		org = "-"
	}
	genAt := data.GeneratedAt
	if genAt.IsZero() {
		genAt = time.Now()
	}
	line(lbl.organization, org)
	line(lbl.period, data.PeriodLabel)
	line(lbl.generatedAt, genAt.Format(lbl.dateLayout))
	if data.GeneratedBy != "" {
		line(lbl.generatedBy, data.GeneratedBy)
	}
	if data.GeneratedByModel != "" {
		line(lbl.writtenBy, data.GeneratedByModel)
	}
	if data.Status == "approved" && data.ApprovedBy != "" {
		val := data.ApprovedBy
		if data.ApprovedAt != nil {
			val = fmt.Sprintf("%s (%s)", data.ApprovedBy, data.ApprovedAt.Format(lbl.dateLayout))
		}
		line(lbl.approvedBy, val)
	}
	pdf.Ln(3)
}

// drawBoardKPIs renders three headline cards: compliance %, active risks, exposure.
func drawBoardKPIs(pdf *fpdf.Fpdf, tr func(string) string, lbl boardLabels, data BoardReportData) {
	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "B", 13)
	setText(pdf, textDark)
	pdf.CellFormat(usableWidth, 8, tr(lbl.postureTitle), "", 1, "L", false, 0, "")

	y := pdf.GetY() + 1
	gap := 6.0
	cardW := (usableWidth - 2*gap) / 3
	cardH := 24.0

	card := func(x float64, title, value string, valueColor rgb) {
		setFill(pdf, cardBg)
		setDraw(pdf, hairline)
		pdf.Rect(x, y, cardW, cardH, "FD")
		pdf.SetXY(x+4, y+3.5)
		pdf.SetFont("Arial", "", 8)
		setText(pdf, textMuted)
		pdf.CellFormat(cardW-8, 4, tr(title), "", 0, "L", false, 0, "")
		pdf.SetXY(x+4, y+9)
		pdf.SetFont("Arial", "B", 17)
		setText(pdf, valueColor)
		pdf.CellFormat(cardW-8, 10, tr(value), "", 0, "L", false, 0, "")
	}

	pct := clampPct(data.OverallCompliancePercent)
	card(pageMarginLeft, lbl.kpiCompliance, fmt.Sprintf("%.0f%%", pct), accentForPct(pct))

	riskColor := critGreen
	if data.RisksCritical > 0 {
		riskColor = critRed
	} else if data.RisksHigh > 0 {
		riskColor = critOrange
	}
	riskVal := fmt.Sprintf("%d", data.RisksTotal)
	card(pageMarginLeft+cardW+gap, lbl.kpiRisks, riskVal, riskColor)
	// sub-note: critical count
	pdf.SetXY(pageMarginLeft+cardW+gap+4, y+19)
	pdf.SetFont("Arial", "", 7.5)
	setText(pdf, textMuted)
	pdf.CellFormat(cardW-8, 4, tr(fmt.Sprintf("%s: %d", lbl.critical, data.RisksCritical)), "", 0, "L", false, 0, "")

	card(pageMarginLeft+2*(cardW+gap), lbl.kpiExposure, data.FinancialExposureLabel, textDark)

	pdf.SetY(y + cardH + 6)
}

// drawRiskChips renders one colored chip per criticality level with its count.
func drawRiskChips(pdf *fpdf.Fpdf, tr func(string) string, lbl boardLabels, data BoardReportData) {
	chips := []struct {
		label string
		count int
		color rgb
	}{
		{lbl.critical, data.RisksCritical, critRed},
		{lbl.high, data.RisksHigh, critOrange},
		{lbl.medium, data.RisksMedium, critAmber},
		{lbl.low, data.RisksLow, critGreen},
	}
	x := pageMarginLeft
	y := pdf.GetY()
	pdf.SetFont("Arial", "", 8.5)
	for _, ch := range chips {
		setFill(pdf, ch.color)
		pdf.Rect(x, y+0.8, 3, 3, "F")
		setText(pdf, textDark)
		txt := fmt.Sprintf(" %s: %d", ch.label, ch.count)
		pdf.SetXY(x+3, y)
		w := pdf.GetStringWidth(tr(txt)) + 6
		pdf.CellFormat(w, 5, tr(txt), "", 0, "L", false, 0, "")
		x += w + 6
	}
	pdf.SetY(y + 8)
}

// drawFrameworksTable renders a compact per-framework compliance table with bars.
func drawFrameworksTable(pdf *fpdf.Fpdf, tr func(string) string, lbl boardLabels, data BoardReportData) {
	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "B", 10)
	setText(pdf, textDark)
	pdf.CellFormat(usableWidth, 6, tr(lbl.frameworksHdr), "", 1, "L", false, 0, "")

	if len(data.Frameworks) == 0 {
		pdf.SetFont("Arial", "I", 9)
		setText(pdf, textMuted)
		pdf.SetX(pageMarginLeft)
		pdf.MultiCell(usableWidth, 5, tr(lbl.noFrameworks), "", "L", false)
		pdf.Ln(2)
		return
	}

	nameW := 70.0
	barW := 70.0
	pctW := usableWidth - nameW - barW
	rowH := 6.0
	for _, f := range data.Frameworks {
		if pdf.GetY()+rowH > pageBottomLimit {
			pdf.AddPage()
		}
		x := pageMarginLeft
		y := pdf.GetY()

		name := f.Name
		if f.Version != "" {
			name = name + " (" + f.Version + ")"
		}
		pdf.SetFont("Arial", "", 9)
		setText(pdf, textDark)
		pdf.SetXY(x, y)
		pdf.CellFormat(nameW, rowH, tr(clip(pdf, tr, name, nameW-2)), "", 0, "L", false, 0, "")

		// bar
		pct := clampPct(f.PercentComplete)
		bx := x + nameW
		by := y + 1.6
		bh := 2.8
		setFill(pdf, barTrack)
		pdf.Rect(bx, by, barW, bh, "F")
		setFill(pdf, accentForPct(pct))
		pdf.Rect(bx, by, barW*pct/100, bh, "F")

		pdf.SetFont("Arial", "B", 9)
		setText(pdf, accentForPct(pct))
		pdf.SetXY(x+nameW+barW, y)
		pdf.CellFormat(pctW, rowH, fmt.Sprintf("%.0f%% (%d/%d)", pct, f.Implemented, f.Applicable), "", 0, "R", false, 0, "")
		pdf.SetY(y + rowH)
	}
	pdf.Ln(3)
}

// drawBoardSection renders a titled paragraph; empty bodies are skipped.
func drawBoardSection(pdf *fpdf.Fpdf, tr func(string) string, title, body string) {
	if body == "" {
		return
	}
	if pdf.GetY()+18 > pageBottomLimit {
		pdf.AddPage()
	}
	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "B", 12)
	setText(pdf, textDark)
	pdf.CellFormat(usableWidth, 7, tr(title), "", 1, "L", false, 0, "")

	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "", 10)
	setText(pdf, rgb{55, 65, 81})
	pdf.MultiCell(usableWidth, 5, tr(body), "", "L", false)
	pdf.Ln(3)
}

// drawRecommendations renders a numbered recommendation list.
func drawRecommendations(pdf *fpdf.Fpdf, tr func(string) string, lbl boardLabels, data BoardReportData) {
	if len(data.Recommendations) == 0 {
		return
	}
	if pdf.GetY()+18 > pageBottomLimit {
		pdf.AddPage()
	}
	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "B", 12)
	setText(pdf, textDark)
	pdf.CellFormat(usableWidth, 7, tr(lbl.recoTitle), "", 1, "L", false, 0, "")

	for i, rec := range data.Recommendations {
		if pdf.GetY()+8 > pageBottomLimit {
			pdf.AddPage()
		}
		y := pdf.GetY()
		// number bullet
		pdf.SetFont("Arial", "B", 10)
		setText(pdf, brandAccent)
		pdf.SetXY(pageMarginLeft, y)
		pdf.CellFormat(7, 5, fmt.Sprintf("%d.", i+1), "", 0, "L", false, 0, "")
		// text
		pdf.SetFont("Arial", "", 10)
		setText(pdf, rgb{55, 65, 81})
		pdf.SetXY(pageMarginLeft+7, y)
		pdf.MultiCell(usableWidth-7, 5, tr(rec), "", "L", false)
		pdf.Ln(1)
	}
}

// clip truncates s (already display text, pre-translation) so its translated width
// fits maxW, adding an ellipsis. Used for the framework name column.
func clip(pdf *fpdf.Fpdf, tr func(string) string, s string, maxW float64) string {
	if pdf.GetStringWidth(tr(s)) <= maxW {
		return s
	}
	runes := []rune(s)
	for len(runes) > 1 {
		runes = runes[:len(runes)-1]
		candidate := string(runes) + "…"
		if pdf.GetStringWidth(tr(candidate)) <= maxW {
			return candidate
		}
	}
	return string(runes)
}
