// Copyright (c) 2026 OpenDefender Contributors
// SPDX-License-Identifier: AGPL-3.0-only
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU Affero General Public License v3.0 (see LICENSE).

package report

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// A4 portrait geometry (mm). Usable width = 210 - 2*margin.
const (
	pageMarginLeft   = 15.0
	pageMarginRight  = 15.0
	pageMarginTop    = 15.0
	pageMarginBottom = 18.0
	usableWidth      = 210.0 - pageMarginLeft - pageMarginRight // 180
	pageBottomLimit  = 297.0 - pageMarginBottom                  // where a row must break
)

// Detailed-table column widths (sum must equal usableWidth = 180).
const (
	colRef    = 22.0
	colName   = 72.0
	colStatus = 30.0
	colEvid   = 18.0
	colSource = 38.0
)

type rgb struct{ r, g, b int }

var (
	brandDark   = rgb{15, 23, 42}    // slate-900 header band
	brandAccent = rgb{37, 99, 235}   // blue-600
	textDark    = rgb{30, 41, 59}    // slate-800
	textMuted   = rgb{100, 116, 139} // slate-500
	hairline    = rgb{203, 213, 225} // slate-300 borders
	zebra       = rgb{243, 246, 250} // very light row tint
	barTrack    = rgb{226, 232, 240} // slate-200

	green = rgb{22, 163, 74}
	amber = rgb{217, 119, 6}
	red   = rgb{220, 38, 38}
	gray  = rgb{100, 116, 139}
)

// statusColor and statusTint return the accent and light-background colors for a status.
func statusColor(s ControlStatus) rgb {
	switch s {
	case StatusImplemented:
		return green
	case StatusInProgress:
		return amber
	case StatusNotImplemented:
		return red
	default:
		return gray
	}
}

func tint(c rgb) rgb {
	// Blend ~12% of the accent color over white for a subtle cell background.
	mix := func(v int) int { return 255 - (255-v)*12/100 }
	return rgb{mix(c.r), mix(c.g), mix(c.b)}
}

// labels holds every fixed (non-data) string, per locale.
type labels struct {
	docTitle     string
	subtitle     string
	organization string
	framework    string
	version      string
	generatedAt  string
	generatedBy  string
	summaryTitle string
	compliant    string
	ofApplicable string
	total        string
	applicable   string
	detailTitle  string
	colRef       string
	colControl   string
	colStatus    string
	colEvidence  string
	colSource    string
	noControls   string
	confidential string
	page         string
	statusNames  map[ControlStatus]string
	dateLayout   string
}

func labelsFor(l Locale) labels {
	if l == LocaleEN {
		return labels{
			docTitle:     "COMPLIANCE REPORT",
			subtitle:     "Official compliance statement",
			organization: "Organization",
			framework:    "Framework",
			version:      "Version",
			generatedAt:  "Generated on",
			generatedBy:  "Generated by",
			summaryTitle: "Executive summary",
			compliant:    "compliant",
			ofApplicable: "of applicable controls implemented",
			total:        "Total controls",
			applicable:   "Applicable",
			detailTitle:  "Controls detail",
			colRef:       "Ref.",
			colControl:   "Control",
			colStatus:    "Status",
			colEvidence:  "Evidence",
			colSource:    "Source",
			noControls:   "No control has been imported into this framework yet.",
			confidential: "Confidential - generated by OpenRisk",
			page:         "Page",
			dateLayout:   "Jan 02, 2006 15:04 MST",
			statusNames: map[ControlStatus]string{
				StatusImplemented:    "Implemented",
				StatusInProgress:     "In progress",
				StatusNotImplemented: "Not implemented",
				StatusNotApplicable:  "Not applicable",
			},
		}
	}
	return labels{
		docTitle:     "RAPPORT DE CONFORMITÉ",
		subtitle:     "Attestation de conformité officielle",
		organization: "Organisation",
		framework:    "Référentiel",
		version:      "Version",
		generatedAt:  "Généré le",
		generatedBy:  "Généré par",
		summaryTitle: "Synthèse exécutive",
		compliant:    "de conformité",
		ofApplicable: "des contrôles applicables mis en œuvre",
		total:        "Contrôles au total",
		applicable:   "Applicables",
		detailTitle:  "Détail des contrôles",
		colRef:       "Réf.",
		colControl:   "Contrôle",
		colStatus:    "Statut",
		colEvidence:  "Preuves",
		colSource:    "Source",
		noControls:   "Aucun contrôle n'a encore été importé dans ce référentiel.",
		confidential: "Confidentiel — généré par OpenRisk",
		page:         "Page",
		dateLayout:   "02/01/2006 15:04 MST",
		statusNames: map[ControlStatus]string{
			StatusImplemented:    "Mis en œuvre",
			StatusInProgress:     "En cours",
			StatusNotImplemented: "Non mis en œuvre",
			StatusNotApplicable:  "Non applicable",
		},
	}
}

// RenderCompliancePDF renders an official compliance report to PDF bytes.
// It is pure: no I/O beyond building the in-memory document.
func RenderCompliancePDF(data ComplianceReportData) ([]byte, error) {
	lbl := labelsFor(data.Locale.normalize())

	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(pageMarginLeft, pageMarginTop, pageMarginRight)
	pdf.SetAutoPageBreak(true, pageMarginBottom)
	pdf.AliasNbPages("{nb}")

	// tr maps UTF-8 into the cp1252 the core fonts expect (French accents, etc.).
	tr := pdf.UnicodeTranslatorFromDescriptor("")

	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Arial", "", 8)
		setText(pdf, textMuted)
		pdf.CellFormat(usableWidth/2, 6, tr(lbl.confidential), "", 0, "L", false, 0, "")
		pdf.CellFormat(usableWidth/2, 6,
			fmt.Sprintf("%s %d/{nb}", lbl.page, pdf.PageNo()),
			"", 0, "R", false, 0, "")
	})

	pdf.AddPage()
	drawHeaderBand(pdf, tr, lbl)
	drawIdentity(pdf, tr, lbl, data)
	drawSummary(pdf, tr, lbl, data)
	drawControlsTable(pdf, tr, lbl, data)

	if pdf.Err() {
		return nil, fmt.Errorf("pdf render error: %w", pdf.Error())
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("pdf output error: %w", err)
	}
	return buf.Bytes(), nil
}

func setText(pdf *fpdf.Fpdf, c rgb)  { pdf.SetTextColor(c.r, c.g, c.b) }
func setFill(pdf *fpdf.Fpdf, c rgb)  { pdf.SetFillColor(c.r, c.g, c.b) }
func setDraw(pdf *fpdf.Fpdf, c rgb)  { pdf.SetDrawColor(c.r, c.g, c.b) }

// drawHeaderBand renders the dark title band at the top of page 1.
func drawHeaderBand(pdf *fpdf.Fpdf, tr func(string) string, lbl labels) {
	setFill(pdf, brandDark)
	pdf.Rect(0, 0, 210, 32, "F")

	// Accent underline
	setFill(pdf, brandAccent)
	pdf.Rect(0, 32, 210, 1.5, "F")

	pdf.SetY(9)
	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "B", 20)
	setText(pdf, rgb{255, 255, 255})
	pdf.CellFormat(usableWidth, 9, tr(lbl.docTitle), "", 1, "L", false, 0, "")

	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "", 10)
	setText(pdf, rgb{203, 213, 225})
	pdf.CellFormat(usableWidth, 6, tr("OpenRisk  -  "+lbl.subtitle), "", 1, "L", false, 0, "")

	pdf.SetY(40)
}

// drawIdentity renders the organization / framework / generation metadata block.
func drawIdentity(pdf *fpdf.Fpdf, tr func(string) string, lbl labels, data ComplianceReportData) {
	line := func(label, value string) {
		pdf.SetX(pageMarginLeft)
		pdf.SetFont("Arial", "B", 10)
		setText(pdf, textMuted)
		pdf.CellFormat(42, 6, tr(label), "", 0, "L", false, 0, "")
		pdf.SetFont("Arial", "", 10)
		setText(pdf, textDark)
		pdf.CellFormat(usableWidth-42, 6, tr(value), "", 1, "L", false, 0, "")
	}

	fw := data.FrameworkName
	if data.FrameworkVersion != "" {
		fw = fw + " (" + data.FrameworkVersion + ")"
	}
	org := data.OrganizationName
	if org == "" {
		org = "-"
	}
	by := data.GeneratedBy
	if by == "" {
		by = "-"
	}
	genAt := data.GeneratedAt
	if genAt.IsZero() {
		genAt = time.Now()
	}

	line(lbl.organization, org)
	line(lbl.framework, fw)
	line(lbl.generatedAt, genAt.Format(lbl.dateLayout))
	line(lbl.generatedBy, by)
	pdf.Ln(3)
}

// drawSummary renders the executive summary: a big compliance %, a progress bar,
// and a per-status breakdown.
func drawSummary(pdf *fpdf.Fpdf, tr func(string) string, lbl labels, data ComplianceReportData) {
	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "B", 13)
	setText(pdf, textDark)
	pdf.CellFormat(usableWidth, 8, tr(lbl.summaryTitle), "", 1, "L", false, 0, "")

	// Card background
	cardY := pdf.GetY() + 1
	cardH := 30.0
	setFill(pdf, zebra)
	setDraw(pdf, hairline)
	pdf.Rect(pageMarginLeft, cardY, usableWidth, cardH, "FD")

	// Big percentage (left)
	pdf.SetXY(pageMarginLeft+4, cardY+4)
	pdf.SetFont("Arial", "B", 30)
	pct := clampPct(data.PercentComplete)
	setText(pdf, accentForPct(pct))
	pdf.CellFormat(46, 14, fmt.Sprintf("%.0f%%", pct), "", 0, "L", false, 0, "")

	pdf.SetXY(pageMarginLeft+4, cardY+19)
	pdf.SetFont("Arial", "", 8)
	setText(pdf, textMuted)
	pdf.CellFormat(52, 5, tr(lbl.ofApplicable), "", 0, "L", false, 0, "")

	// Progress bar (right of the percentage)
	barX := pageMarginLeft + 58
	barW := usableWidth - 62
	barY := cardY + 8
	barH := 5.0
	setFill(pdf, barTrack)
	pdf.Rect(barX, barY, barW, barH, "F")
	setFill(pdf, accentForPct(pct))
	pdf.Rect(barX, barY, barW*pct/100, barH, "F")

	// Status breakdown chips under the bar
	chips := []struct {
		s     ControlStatus
		count int
	}{
		{StatusImplemented, data.Implemented},
		{StatusInProgress, data.InProgress},
		{StatusNotImplemented, data.NotImplemented},
		{StatusNotApplicable, data.NotApplicable},
	}
	chipY := barY + 9
	chipX := barX
	pdf.SetFont("Arial", "", 8)
	for _, ch := range chips {
		c := statusColor(ch.s)
		setFill(pdf, c)
		pdf.Rect(chipX, chipY+1, 3, 3, "F")
		setText(pdf, textDark)
		txt := fmt.Sprintf(" %s: %d", lbl.statusNames[ch.s], ch.count)
		pdf.SetXY(chipX+3, chipY)
		w := pdf.GetStringWidth(tr(txt)) + 6
		pdf.CellFormat(w, 5, tr(txt), "", 0, "L", false, 0, "")
		chipX += w + 4
	}

	pdf.SetY(cardY + cardH + 6)
}

// drawControlsTable renders the detailed, paginated controls table.
func drawControlsTable(pdf *fpdf.Fpdf, tr func(string) string, lbl labels, data ComplianceReportData) {
	pdf.SetX(pageMarginLeft)
	pdf.SetFont("Arial", "B", 13)
	setText(pdf, textDark)
	pdf.CellFormat(usableWidth, 8, tr(lbl.detailTitle), "", 1, "L", false, 0, "")
	pdf.Ln(1)

	if len(data.Controls) == 0 {
		pdf.SetFont("Arial", "I", 10)
		setText(pdf, textMuted)
		pdf.SetX(pageMarginLeft)
		pdf.MultiCell(usableWidth, 6, tr(lbl.noControls), "", "L", false)
		return
	}

	drawTableHeader := func() {
		setFill(pdf, brandDark)
		setText(pdf, rgb{255, 255, 255})
		pdf.SetFont("Arial", "B", 8.5)
		pdf.SetX(pageMarginLeft)
		pdf.CellFormat(colRef, 7, tr(lbl.colRef), "", 0, "L", true, 0, "")
		pdf.CellFormat(colName, 7, tr(lbl.colControl), "", 0, "L", true, 0, "")
		pdf.CellFormat(colStatus, 7, tr(lbl.colStatus), "", 0, "L", true, 0, "")
		pdf.CellFormat(colEvid, 7, tr(lbl.colEvidence), "", 0, "C", true, 0, "")
		pdf.CellFormat(colSource, 7, tr(lbl.colSource), "", 0, "L", true, 0, "")
		pdf.Ln(7)
	}

	drawTableHeader()

	lineH := 4.4
	for i, row := range data.Controls {
		// Measure wrapped lines for name (font 9) and source (font 7.5) to size the row.
		// NOTE: we deliberately do NOT use fpdf.SplitText here — it indexes the font's
		// 256-entry width table by rune and panics on any rune > 255 (em dash, ligatures,
		// typographic quotes). wrapText measures the cp1252-translated string byte-wise
		// via GetStringWidth, which matches how MultiCell renders it below.
		pdf.SetFont("Arial", "", 9)
		nameLines := wrapText(pdf, tr(row.Name), colName-3)
		pdf.SetFont("Arial", "", 7.5)
		srcLines := wrapText(pdf, tr(row.SourceReference), colSource-3)

		nLines := len(nameLines)
		if len(srcLines) > nLines {
			nLines = len(srcLines)
		}
		if nLines == 0 {
			nLines = 1
		}
		rowH := float64(nLines)*lineH + 3

		// Page break: repeat the header on the new page.
		if pdf.GetY()+rowH > pageBottomLimit {
			pdf.AddPage()
			drawTableHeader()
		}

		x0 := pageMarginLeft
		y0 := pdf.GetY()

		// Zebra background for odd rows.
		if i%2 == 1 {
			setFill(pdf, zebra)
			pdf.Rect(x0, y0, usableWidth, rowH, "F")
		}

		// Status cell tinted background.
		sc := statusColor(row.Status)
		setFill(pdf, tint(sc))
		pdf.Rect(x0+colRef+colName, y0, colStatus, rowH, "F")

		// Column borders (hairline).
		setDraw(pdf, hairline)
		pdf.Rect(x0, y0, usableWidth, rowH, "D")
		xline := x0
		for _, w := range []float64{colRef, colName, colStatus, colEvid} {
			xline += w
			pdf.Line(xline, y0, xline, y0+rowH)
		}

		// Ref (vertically centered)
		pdf.SetFont("Arial", "B", 8.5)
		setText(pdf, textDark)
		pdf.SetXY(x0+1, y0)
		pdf.CellFormat(colRef-1, rowH, tr(row.ReferenceCode), "", 0, "LM", false, 0, "")

		// Name — rendered line-by-line from the exact lines we measured, so the
		// wrapping matches the row height and nothing clips.
		pdf.SetFont("Arial", "", 9)
		setText(pdf, textDark)
		drawLines(pdf, nameLines, x0+colRef+1.5, y0+1.5, colName-3, lineH)

		// Status label in its accent color, centered
		pdf.SetFont("Arial", "B", 8)
		setText(pdf, sc)
		pdf.SetXY(x0+colRef+colName, y0)
		pdf.CellFormat(colStatus, rowH, tr(lbl.statusNames[row.Status]), "", 0, "CM", false, 0, "")

		// Evidence count, centered
		pdf.SetFont("Arial", "", 9)
		if row.EvidenceCount > 0 {
			setText(pdf, green)
		} else {
			setText(pdf, textMuted)
		}
		pdf.SetXY(x0+colRef+colName+colStatus, y0)
		pdf.CellFormat(colEvid, rowH, fmt.Sprintf("%d", row.EvidenceCount), "", 0, "CM", false, 0, "")

		// Source (top-aligned, wrapped, small)
		pdf.SetFont("Arial", "", 7.5)
		setText(pdf, textMuted)
		drawLines(pdf, srcLines, x0+colRef+colName+colStatus+colEvid+1.5, y0+1.5, colSource-3, lineH)

		pdf.SetY(y0 + rowH)
	}
}

// wrapText greedily word-wraps s (already translated to the current font's
// cp1252 encoding) so each line's rendered width stays within maxW. Width is
// measured with GetStringWidth, which iterates bytes — safe for any translated
// input, unlike fpdf.SplitText. A single word wider than maxW is kept on its
// own line (it may overflow slightly rather than be dropped).
func wrapText(pdf *fpdf.Fpdf, s string, maxW float64) []string {
	var lines []string
	for _, para := range strings.Split(s, "\n") {
		words := strings.Fields(para)
		if len(words) == 0 {
			lines = append(lines, "")
			continue
		}
		cur := ""
		for _, w := range words {
			trial := w
			if cur != "" {
				trial = cur + " " + w
			}
			if cur == "" || pdf.GetStringWidth(trial) <= maxW {
				cur = trial
			} else {
				lines = append(lines, cur)
				cur = w
			}
		}
		if cur != "" {
			lines = append(lines, cur)
		}
	}
	if len(lines) == 0 {
		return []string{""}
	}
	return lines
}

// drawLines renders pre-wrapped, already-translated lines top-down at (x, y).
func drawLines(pdf *fpdf.Fpdf, lines []string, x, y, w, lineH float64) {
	for i, ln := range lines {
		pdf.SetXY(x, y+float64(i)*lineH)
		pdf.CellFormat(w, lineH, ln, "", 0, "L", false, 0, "")
	}
}

func clampPct(p float64) float64 {
	if p < 0 {
		return 0
	}
	if p > 100 {
		return 100
	}
	return p
}

// accentForPct grades the headline color: red < 50% <= amber < 80% <= green.
func accentForPct(p float64) rgb {
	switch {
	case p >= 80:
		return green
	case p >= 50:
		return amber
	default:
		return red
	}
}
