// Copyright (c) 2026 OpenDefender Contributors
// SPDX-License-Identifier: BUSL-1.1
// This Source Code Form is subject to the terms of the Business Source License, Version 1.1.
// If a copy of the BUSL was not distributed with this file, You can obtain one at https://mariadb.com/bsl11/

package compliance

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/opendefender/openrisk/internal/domain"
	"github.com/opendefender/openrisk/pkg/report"
)

// OrganizationLookup is the minimal port the report needs to resolve an
// organization's display name for the cover page. GormOrganizationRepository
// satisfies it.
type OrganizationLookup interface {
	GetByID(ctx context.Context, id uuid.UUID) (*domain.Organization, error)
}

// UserLookup is the minimal port to resolve who requested the report.
// GormUserRepository satisfies it.
type UserLookup interface {
	GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error)
}

// GenerateComplianceReportUseCase assembles all tenant-scoped data needed to
// render an official compliance report for one framework: the framework
// identity, every control (tenant-scoped) with its status, per-control evidence
// counts, and the compliance tally. It returns render-ready data — the PDF
// rendering itself lives in pkg/report and is done by the caller, keeping this
// use case free of presentation concerns and easy to unit-test on its output.
type GenerateComplianceReportUseCase struct {
	repo domain.ComplianceRepository
	orgs OrganizationLookup
	usrs UserLookup
}

func NewGenerateComplianceReportUseCase(
	repo domain.ComplianceRepository,
	orgs OrganizationLookup,
	usrs UserLookup,
) *GenerateComplianceReportUseCase {
	return &GenerateComplianceReportUseCase{repo: repo, orgs: orgs, usrs: usrs}
}

// Execute gathers the report data for (tenantID, frameworkID). requestedBy is
// the ID of the user asking for the report (used only for the "generated by"
// line). locale selects the fixed-label language.
//
// The framework is global; controls and evidences are strictly tenant-scoped,
// so a tenant only ever sees its own advancement even on a shared framework.
func (uc *GenerateComplianceReportUseCase) Execute(
	ctx context.Context,
	tenantID uuid.UUID,
	frameworkID uuid.UUID,
	requestedBy uuid.UUID,
	locale report.Locale,
) (*report.ComplianceReportData, error) {
	fw, err := uc.repo.GetFrameworkByID(ctx, frameworkID, tenantID)
	if err != nil {
		return nil, err
	}
	if fw == nil {
		return nil, domain.NewNotFoundError("framework", frameworkID)
	}

	controls, err := uc.repo.ListControlsByFramework(ctx, tenantID, frameworkID)
	if err != nil {
		return nil, err
	}

	evidenceCounts, err := uc.repo.CountEvidencesByFramework(ctx, tenantID, frameworkID)
	if err != nil {
		return nil, err
	}

	data := &report.ComplianceReportData{
		Locale:           locale,
		OrganizationName: uc.resolveOrgName(ctx, tenantID),
		FrameworkName:    fw.Name,
		FrameworkVersion: fw.Version,
		FrameworkDesc:    fw.Description,
		GeneratedAt:      time.Now(),
		GeneratedBy:      uc.resolveUserLabel(ctx, requestedBy),
		Total:            len(controls),
	}

	data.Controls = make([]report.ReportControlRow, 0, len(controls))
	for _, c := range controls {
		switch c.Status {
		case domain.ControlStatusImplemented:
			data.Implemented++
		case domain.ControlStatusInProgress:
			data.InProgress++
		case domain.ControlStatusNotApplicable:
			data.NotApplicable++
		default:
			data.NotImplemented++
		}
		data.Controls = append(data.Controls, report.ReportControlRow{
			ReferenceCode:   c.ReferenceCode,
			Name:            c.Name,
			Status:          report.ControlStatus(c.Status),
			SourceReference: c.SourceReference,
			EvidenceCount:   evidenceCounts[c.ID],
		})
	}

	// Applicable = everything except explicitly not-applicable controls. Percent
	// mirrors GetComplianceProgressUseCase so the report and the UI gauge agree.
	data.Applicable = data.Total - data.NotApplicable
	if data.Applicable > 0 {
		data.PercentComplete = float64(data.Implemented) / float64(data.Applicable) * 100
	}

	return data, nil
}

// resolveOrgName best-effort resolves the organization display name. A missing
// org (or lookup error) must not fail report generation — the cover simply
// shows a dash instead.
func (uc *GenerateComplianceReportUseCase) resolveOrgName(ctx context.Context, tenantID uuid.UUID) string {
	if uc.orgs == nil {
		return ""
	}
	org, err := uc.orgs.GetByID(ctx, tenantID)
	if err != nil || org == nil {
		return ""
	}
	return org.Name
}

// resolveUserLabel best-effort resolves who requested the report, preferring the
// full name, then email. Never fails report generation.
func (uc *GenerateComplianceReportUseCase) resolveUserLabel(ctx context.Context, userID uuid.UUID) string {
	if uc.usrs == nil || userID == uuid.Nil {
		return ""
	}
	u, err := uc.usrs.GetByID(ctx, userID)
	if err != nil || u == nil {
		return ""
	}
	if u.FullName != "" {
		return u.FullName
	}
	return u.Email
}
