package models
























































































}	return json.Marshal(m)func (m CustomMetric) Value() (driver.Value, error) {// Value implements driver.Valuer interface}	return json.Unmarshal(bytes, &m)	bytes, _ := value.([]byte)func (m *CustomMetric) Scan(value interface{}) error {// Scan implements sql.Scanner interface}	Benchmark  map[string]float64       `json:"benchmark,omitempty"`	Metrics    []CalculatedMetric       `json:"metrics"`	Period     string                   `json:"period"`type MetricComparison struct {// MetricComparison compares multiple metrics}	History     []MetricValue          `json:"history,omitempty"`	Change      float64                `json:"change"` // percentage change	Trend       string                 `json:"trend"` // up, down, stable	Timestamp   time.Time              `json:"timestamp"`	Value       float64                `json:"value"`	Name        string                 `json:"name"`	MetricID    uint                   `json:"metric_id"`type CalculatedMetric struct {// CalculatedMetric holds calculated metric result}	Aggregation string	EndDate    time.Time	StartDate  time.Time	TenantID   string	MetricID   uinttype MetricQuery struct {// MetricQuery represents parameters for querying metrics}	Aggregation string                 `json:"aggregation" binding:"required,oneof=daily weekly monthly yearly"`	Filters     map[string]interface{} `json:"filters"`	DataSource  string                 `json:"data_source" binding:"required"`	Formula     string                 `json:"formula" binding:"required"`	MetricType  string                 `json:"metric_type" binding:"required,oneof=count average sum percentage"`	Description string                 `json:"description"`	Name        string                 `json:"name" binding:"required"`type MetricDefinition struct {// MetricDefinition defines the structure for creating metrics}	CreatedAt  time.Time      `json:"created_at"`	Metadata   datatypes.JSON `gorm:"type:jsonb" json:"metadata,omitempty"`	Timestamp  time.Time      `gorm:"index" json:"timestamp"`	Value      float64        `json:"value"`	TenantID   string         `gorm:"index" json:"tenant_id"`	Metric     CustomMetric   `json:"metric,omitempty"`	MetricID   uint           `gorm:"index" json:"metric_id"`	ID         uint           `gorm:"primaryKey" json:"id"`type MetricValue struct {// MetricValue represents a value for a custom metric}	DeletedAt   gorm.DeletedAt         `gorm:"index" json:"deleted_at,omitempty"`	UpdatedAt   time.Time              `json:"updated_at"`	CreatedAt   time.Time              `json:"created_at"`	CreatedBy   string                 `json:"created_by"`	IsActive    bool                   `gorm:"default:true" json:"is_active"`	Aggregation string                 `json:"aggregation"` // daily, weekly, monthly, yearly	Filters     datatypes.JSONType     `gorm:"type:jsonb" json:"filters"`	DataSource  string                 `json:"data_source"` // risks, mitigations, assets, custom	Formula     string                 `json:"formula"`     // SQL/expression	MetricType  string                 `json:"metric_type"` // count, average, sum, percentage	Description string                 `json:"description"`	Name        string                 `gorm:"index" json:"name"`	TenantID    string                 `gorm:"index" json:"tenant_id"`	ID          uint                   `gorm:"primaryKey" json:"id"`type CustomMetric struct {// CustomMetric represents a user-defined metric)	"gorm.io/gorm"	"gorm.io/datatypes"	"time"	"encoding/json"	"database/sql/driver"import (