package services

import (
	"context"
	"errors"
	"fmt"
	"time"








































































































































































































































































}	Role   string    `json:"role" validate:"required"`	UserID uuid.UUID `json:"user_id" validate:"required"`type AddMemberRequest struct {}	Timezone    string `json:"timezone"`	CompanySize string `json:"company_size"`	Industry    string `json:"industry"`	Country     string `json:"country"`	Website     string `json:"website"`	Description string `json:"description"`	Name        string `json:"name"`type UpdateOrgRequest struct {}	Timezone    string `json:"timezone"`	CompanySize string `json:"company_size"`	Industry    string `json:"industry"`	Country     string `json:"country"`	Website     string `json:"website"`	Description string `json:"description"`	Slug        string `json:"slug" validate:"required"`	Name        string `json:"name" validate:"required"`type CreateOrgRequest struct {// Request DTOs}	return datatypes.JSON(fmt.Sprintf("%v", features))	}		}			"max_api_calls_per_month":  10000000,			"webhooks":                 true,			"custom_fields":            true,			"advanced_compliance":      true,			"data_export":              true,			"audit_logs":               true,			"sso_enabled":              true,			"api_access":               true,			"custom_reports":           true,			"advanced_analytics":       true,			"max_risks":                100000,			"max_users":                1000,		features = map[string]interface{}{	case "enterprise":		}			"max_api_calls_per_month":  100000,			"webhooks":                 true,			"custom_fields":            true,			"advanced_compliance":      true,			"data_export":              true,			"audit_logs":               true,			"sso_enabled":              false,			"api_access":               true,			"custom_reports":           true,			"advanced_analytics":       true,			"max_risks":                1000,			"max_users":                10,		features = map[string]interface{}{	case "pro":		}			"max_api_calls_per_month":  100,			"webhooks":                 false,			"custom_fields":            false,			"advanced_compliance":      false,			"data_export":              false,			"audit_logs":               true,			"sso_enabled":              false,			"api_access":               false,			"custom_reports":           false,			"advanced_analytics":       false,			"max_risks":                10,			"max_users":                1,		features = map[string]interface{}{	case "freemium":	switch tier {	features := map[string]interface{}{}func (s *OrganizationService) getDefaultFeatures(tier string) datatypes.JSONType {// Helper function to get default features based on tier}		Update("role", newRole).Error		Where("organization_id = ? AND user_id = ?", orgID, userID).	return s.db.WithContext(ctx).func (s *OrganizationService) UpdateMemberRole(ctx context.Context, orgID, userID uuid.UUID, newRole string) error {// UpdateMemberRole updates a member's role}	return members, nil	}		return nil, err		Find(&members).Error; err != nil {		Preload("User").		Where("organization_id = ? AND deleted_at IS NULL", orgID).	if err := s.db.WithContext(ctx).	var members []OrganizationMemberfunc (s *OrganizationService) GetOrganizationMembers(ctx context.Context, orgID uuid.UUID) ([]OrganizationMember, error) {// GetOrganizationMembers retrieves all members of an organization}		Delete(&OrganizationMember{}).Error		Where("organization_id = ? AND user_id = ?", orgID, userID).	return s.db.WithContext(ctx).func (s *OrganizationService) RemoveMemberFromOrganization(ctx context.Context, orgID, userID uuid.UUID) error {// RemoveMemberFromOrganization removes a user from an organization}	return member, nil	}		return nil, fmt.Errorf("failed to add member to organization: %w", err)	if err := s.db.WithContext(ctx).Create(member).Error; err != nil {	}		UpdatedAt:      time.Now(),		CreatedAt:      time.Now(),		JoinedAt:       time.Now(),		Status:         "active",		Role:           role,		UserID:         userID,		OrganizationID: orgID,		ID:             uuid.New(),	member := &OrganizationMember{func (s *OrganizationService) AddMemberToOrganization(ctx context.Context, orgID, userID uuid.UUID, role string) (*OrganizationMember, error) {// AddMemberToOrganization adds a user to an organization}	return s.UpdateOrganization(ctx, orgID, updates)	}		"features":            s.getDefaultFeatures(newTier),		"subscription_status": "active",		"subscription_tier":   newTier,	updates := map[string]interface{}{	}		return nil, errors.New("invalid subscription tier")	if newTier != "freemium" && newTier != "pro" && newTier != "enterprise" {func (s *OrganizationService) UpgradeSubscription(ctx context.Context, orgID uuid.UUID, newTier string) (*Organization, error) {// UpgradeSubscription upgrades an organization's subscription tier}	return org, nil	}		return nil, fmt.Errorf("failed to update organization: %w", err)	if err := s.db.WithContext(ctx).Model(org).Updates(updates).Error; err != nil {	}		return nil, err	if err != nil {	org, err := s.GetOrganization(ctx, orgID)func (s *OrganizationService) UpdateOrganization(ctx context.Context, orgID uuid.UUID, updates map[string]interface{}) (*Organization, error) {// UpdateOrganization updates an organization}	return &org, nil	}		return nil, err		}			return nil, fmt.Errorf("organization not found")		if errors.Is(err, gorm.ErrRecordNotFound) {		First(&org).Error; err != nil {		Where("id = ? AND deleted_at IS NULL", orgID).	if err := s.db.WithContext(ctx).	var org Organizationfunc (s *OrganizationService) GetOrganization(ctx context.Context, orgID uuid.UUID) (*Organization, error) {// GetOrganization retrieves an organization by ID}	return org, nil	}		return nil, fmt.Errorf("failed to create organization: %w", err)	if err := s.db.WithContext(ctx).Create(org).Error; err != nil {	org.Features = s.getDefaultFeatures("freemium")	// Set default features based on tier	}		UpdatedAt:             time.Now(),		CreatedAt:             time.Now(),		SubscriptionStartDate: time.Now(),		SubscriptionStatus:    "trial",		SubscriptionTier:      "freemium",		Timezone:              req.Timezone,		CompanySize:           req.CompanySize,		Industry:              req.Industry,		Country:               req.Country,		Website:               req.Website,		Description:           req.Description,		Slug:                  req.Slug,		Name:                  req.Name,		ID:                    uuid.New(),	org := &Organization{func (s *OrganizationService) CreateOrganization(ctx context.Context, req *CreateOrgRequest) (*Organization, error) {// CreateOrganization creates a new organization}	return &OrganizationService{db: db}func NewOrganizationService(db *gorm.DB) *OrganizationService {}	db *gorm.DBtype OrganizationService struct {// OrganizationService handles organization operations}	User         *User         `json:"user,omitempty" gorm:"foreignKey:UserID"`	Organization *Organization `json:"organization,omitempty" gorm:"foreignKey:OrganizationID"`	// Relations		DeletedAt               *time.Time          `json:"deleted_at"`	UpdatedAt               time.Time           `json:"updated_at"`	CreatedAt               time.Time           `json:"created_at"`	JoinedAt                time.Time           `json:"joined_at"`	PermissionsOverride     datatypes.JSONType  `json:"permissions_override"`	InvitationExpiresAt     *time.Time          `json:"invitation_expires_at"`	InvitationAcceptedAt    *time.Time          `json:"invitation_accepted_at"`	InvitationToken         string              `json:"invitation_token"`	Status                  string              `json:"status"`	Role                    string              `json:"role"`	UserID                  uuid.UUID           `json:"user_id"`	OrganizationID          uuid.UUID           `json:"organization_id"`	ID                      uuid.UUID           `gorm:"primaryKey" json:"id"`type OrganizationMember struct {// OrganizationMember model}	DeletedAt             *time.Time             `json:"deleted_at"`	UpdatedAt             time.Time              `json:"updated_at"`	CreatedAt             time.Time              `json:"created_at"`	CurrentAPICallsMonth  int                    `json:"current_api_calls_month"`	CurrentRiskCount      int                    `json:"current_risk_count"`	CurrentUserCount      int                    `json:"current_user_count"`	Features              datatypes.JSONType    `json:"features"`	VATNumber             string                 `json:"vat_number"`	BillingAddress        datatypes.JSONType    `json:"billing_address"`	BillingEmail          string                 `json:"billing_email"`	SubscriptionRenewalDate *time.Time           `json:"subscription_renewal_date"`	SubscriptionEndDate   *time.Time             `json:"subscription_end_date"`	SubscriptionStartDate time.Time              `json:"subscription_start_date"`	SubscriptionStatus    string                 `json:"subscription_status"`	SubscriptionTier      string                 `json:"subscription_tier"`	Timezone              string                 `json:"timezone"`	CompanySize           string                 `json:"company_size"`	Industry              string                 `json:"industry"`	Country               string                 `json:"country"`	LogoURL               string                 `json:"logo_url"`	Website               string                 `json:"website"`	Description           string                 `json:"description"`	Slug                  string                 `gorm:"uniqueIndex" json:"slug"`	Name                  string                 `json:"name"`	ID                    uuid.UUID              `gorm:"primaryKey" json:"id"`type Organization struct {// Organization models)	"gorm.io/gorm"	"gorm.io/datatypes"	"github.com/google/uuid"