apiVersion: v2
name: openrisk
description: A Helm chart for OpenRisk - Enterprise Risk Management Platform
type: application
version: 1.1.0-rc.1
appVersion: "1.1.0-rc.1"
home: https://github.com/alex-dembele/openrisk
sources:
  - https://github.com/alex-dembele/openrisk
maintainers:
  - name: OpenDefender Team
    email: team@opendefender.io
keywords:
  - risk-management
  - enterprise-security
  - kubernetes
  - docker
dependencies: []
annotations:
  category: Security
  licenseUrl: https://mariadb.com/bsl11/
  releaseNotes: "Phase 5 - Kubernetes deployment for OpenRisk"
